In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = pd.read_excel('Bike.xlsx')
df

ID  Age  Gender  Occupation  Phone Type  Current Bike  Relationship  \
0        1   53       1           4           2             4             3   
1        2   27       0           3           1             1             1   
2        3   39       0           2           2             4             4   
3        4   20       0           2           3             1             4   
4        5   29       1           1           2             4             3   
...    ...  ...     ...         ...         ...           ...           ...   
1513  1514   19       1           1           3             3             2   
1514  1515   18       1           1           3             2             4   
1515  1516   24       0           1           3             4             4   
1516  1517   23       0           1           3             3             1   
1517  1518   18       1           1           3             4             1   

      Response  
0            0  
1            1  
2            0  
3            0  
4            1  
...        ...  
1513         1  
1514         1  
1515         1  
1516         1  
1517         1  

[1518 rows x 8 columns]

In [3]:
df = df.drop('ID', axis=1)

In [4]:
df.head()

Age  Gender  Occupation  Phone Type  Current Bike  Relationship  Response
0   53       1           4           2             4             3         0
1   27       0           3           1             1             1         1
2   39       0           2           2             4             4         0
3   20       0           2           3             1             4         0
4   29       1           1           2             4             3         1

In [5]:
x = df.drop('Response',axis=1)
x.head()

Age  Gender  Occupation  Phone Type  Current Bike  Relationship
0   53       1           4           2             4             3
1   27       0           3           1             1             1
2   39       0           2           2             4             4
3   20       0           2           3             1             4
4   29       1           1           2             4             3

In [6]:
y = df[['Response']]
y.head()

Response
0         0
1         1
2         0
3         0
4         1

In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3, random_state=50)

In [8]:
xtrain.shape

(1062, 6)

In [9]:
ytrain.shape

(1062, 1)

In [10]:
xtest.shape

(456, 6)

In [11]:
ytest.shape

(456, 1)

In [12]:
lr = LogisticRegression()

In [13]:
lr.fit(xtrain,ytrain)

C:\Users\kaush\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [14]:
lr.coef_

array([[-0.07891396,  0.6049652 , -0.56191472,  0.40236276,  0.19469102,
        -0.20649892]])

In [15]:
pred = lr.predict(xtest)
pred

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,

In [16]:
accuracy_score(ytest,pred)

0.7719298245614035

In [17]:
confusion_matrix(ytest,pred)

array([[142,  55],
       [ 49, 210]], dtype=int64)